### ISSUE TITLE
Not specifying `count` parameter for enabling GPU access breaks the feature, while docs claim it is not necessary

### ISSUE THREAD

**Issue by C0rn3j** [docker/docs#20588]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

    count. This value, specified as an integer or the value all, represents the number of GPU devices that should be reserved (providing the host holds that number of GPUs). If count is set to all or not specified, all GPUs available on the host are used by default.

This is the compose file of mine that if you remove the `count: all` line from, it will break and GPU won't be available in the container:
```yaml
services:
  server:
    image: ghcr.io/matatonic/openedai-speech
    container_name: openedai-speech
    ports:
      - "8000:8000"
    volumes:
      - tts-voices:/app/voices
      - tts-config:/app/config
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
#              count: all
              capabilities: [gpu]

volumes:
  tts-voices:
  tts-config:
```

```python
root@b14607261e05:/app# tts --model_name tts_models/multilingual/multi-dataset/xtts_v2 --text "Bugün okula gitmek istemiyorum." --speaker_wav /app/voices/nova.wav --language_idx tr --use_cuda true
tts_models/multilingual/multi-dataset/xtts_v2 is already downloaded.
Using model: xtts
Traceback (most recent call last):
  File "/usr/local/bin/tts", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/TTS/bin/synthesize.py", line 441, in main
    ).to(device)
      ^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1173, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/usr/local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 804, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1159, in convert
    return t.to(
           ^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/cuda/__init__.py", line 293, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
```

### Location

https://docs.docker.com/compose/gpu-support/

### Suggestion

Either fix the documentation to specify one of `count` or `device_ids` is required, which is the actual behavior at the moment, or change the behavior to follow the documentation.

**Comment by C0rn3j** [comment]
@aevesdocker @glours
